import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";
import { adlam } from './font'
import { GameProvider } from "./context/GameProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={adlam.variable}>
      <body
         className="font-display" style={{ fontFamily: 'var(--font-adlam)' }}
      >
        <div className="flex justify-items-center">
          <div className="mobile-container">

            <GameProvider>
            <NavBar>
              {children}
            </NavBar>
              </GameProvider>
              </div>
        </div>
      </body>
    </html>
  );
}
